name: tiny-beast-dictionary # you probably want to 'snapcraft register <name>'
title: Tiny Beast Dictionary
base: core20 # the base snap is the execution environment for this snap
version: '1.2.3' # just for humans, typically '1.2+git' or '1.3.2'
summary: Tiny version of Google Translate capable of using huge offline dictionaries # 79 char long summary
description: |
  **Tiny Beast is an app which can be as tiny as less than 10 MB (though the snap version is 209 MB) or be huge by downloading dictionaries for it!**
  - Online Mode: If you're learning a new language, maybe watching some movies and want to know the translation of the words actors/actresses say in no time, this mode is useful. It mimics the Google Translate service.
  - Offline Mode: For those who want to have dictionaries in their computer's disk storage without having to make them themselves, there are several huge dictionaries (thanks to kaikki.org) dedicated to popular languages in which detailed information such as root of words (etymology), variations in different countries etc. are provided.
license: "GFDL-1.3-or-later"
icon: icon.png

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
architectures:
  - amd64
  - i386

parts:
  load-front:
    plugin: npm
    npm-node-version: 14.17.0
    source: .

  tiny-beast-dictionary:
    plugin: rust
    after:
      - load-front
    # See 'snapcraft plugins'
    source: .
    source-subdir: ./src-tauri
    build-packages:
      - libwebkit2gtk-4.0-dev
      - libasound2-dev
      - build-essential
      - curl
      - wget
      - libssl-dev
      - libgtk-3-dev
      - libayatana-appindicator3-dev
      - librsvg2-dev
    override-build: |
      npm install
      npm run build
      snapcraftctl build

apps:
  tiny-beast-dictionary:
    command: bin/tiny-beast-dictionary