name: tiny-beast-dictionary # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: '1.2.3' # just for humans, typically '1.2+git' or '1.3.2'
summary: Tiny App for online/offline dictionaries.  # 79 char long summary
description: |
  It works using google translate api and Kaikki.org database to download massive dictionaries for offline use.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

parts:
  tiny-beast-dictionary:
    # See 'snapcraft plugins'
    plugin: rust
    source: .

apps:
  tiny-beast-dictionary:
    command: bin/tiny-beast-dictionary