name: tiny-beast-dictionary # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: '1.2.3' # just for humans, typically '1.2+git' or '1.3.2'
summary: Tiny App for online/offline dictionaries.  # 79 char long summary
description: |
  It works using google translate api and Kaikki.org database to download massive dictionaries for offline use.
license: "GFDL"

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
architectures:
  - amd64

parts:
  tiny-beast-dictionary:
    # See 'snapcraft plugins'
    plugin: rust
    source: ./src-tauri
    build-packages:
      - libwebkit2gtk-4.0-dev
      - build-essential
      - curl
      - wget
      - libssl-dev
      - libgtk-3-dev
      - libayatana-appindicator3-dev
      - librsvg2-dev
    stage-packages:
      - libwebkit2gtk-4.0-dev
      - build-essential
      - curl
      - wget
      - libssl-dev
      - libgtk-3-dev
      - libayatana-appindicator3-dev
      - librsvg2-dev

apps:
  tiny-beast-dictionary:
    command: bin/tiny-beast-dictionary