name: tiny-dictionary # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: '0.2.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Tiny App for online/offline dictionaries backed by Google Translate Service  # 79 char long summary
description: |
  It works using google translate api and offline dictionary (english-to-persian for now) databases.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

parts:
  tiny-dictionary:
    # See 'snapcraft plugins'
    plugin: rust
    source: .

apps:
  tiny-dictionary:
    command: bin/tiny-dictionary