name: tiny-beast-dictionary # you probably want to 'snapcraft register <name>'
title: Tiny Beast Dictionary
base: core22 # the base snap is the execution environment for this snap
version: "1.7.39" # just for humans, typically '1.2+git' or '1.3.2'
summary: Tiny version of Google Translate capable of using huge offline dictionaries # 79 char long summary
description: |
  **Tiny Beast is an app which can be as tiny as less than 9 MB or be huge by downloading free dictionaries for it!**
  - Online Mode: It mimics the Google Translate service.
  - Offline Mode: For those who want to have dictionaries in their computer's disk storage without having to make them themselves, there are several huge dictionaries (thanks to kaikki.org) dedicated to popular languages in which detailed information such as root of words (etymology), variations in different countries etc. are provided.
license: "GFDL-1.3-or-later"
icon: icon.png

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
architectures:
  - amd64
environment:
  ALWAYS_USE_PULSEAUDIO: '1'
  PATH: /snap/tiny-beast-dictionary/current:$PATH

apps:
  tiny-beast-dictionary:
    command-chain: ["snap/command-chain/alsa-launch"]
    command: tiny-beast-dictionary
    extensions:
      - gnome
    desktop: tiny-beast-dictionary.desktop
    plugs:
      - home
      - alsa
      - audio-playback
      - network-status
      - network

layout:
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib
  /usr/share/alsa:
    bind: $SNAP/usr/share/alsa
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.0:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.0

parts:
  alsa-mixin:
    plugin: dump
    source: https://github.com/diddlesnaps/snapcraft-alsa.git
    source-subdir: snapcraft-assets
    build-packages:
      - libasound2-dev
    stage-packages:
      - libasound2
      - libasound2-plugins
      - yad
    stage:
      - etc/asound.conf
      - snap/command-chain/alsa-launch
      - usr/bin/yad*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libasound*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libdnsfile*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libFLAC*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libjack*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libpulse*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libsamplerate*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libspeex*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libvorbis*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio
  dump-binary:
    after: [alsa-mixin]
    plugin: dump
    source: ./src-tauri
    stage:
      - icons
      - tiny-beast-dictionary
      - tiny-beast-dictionary.desktop
      - xsel
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.0
    prime:
      - icons
      - tiny-beast-dictionary
      - tiny-beast-dictionary.desktop
      - xsel
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.0
    stage-packages:
      - libwebkit2gtk-4.0-37
      - libasound2





    #   build-packages:
    #   - libwebkit2gtk-4.0-dev
    #   - libasound2-dev
    #   - build-essential
    #   - curl
    #   - wget
    #   - libssl-dev
    #   - libgtk-3-dev
    #   - libayatana-appindicator3-dev
    #   - librsvg2-dev
    # stage-packages:
    #   - libasound2
    #   - libatk-bridge2.0-0
    #   - libatk1.0-0
    #   - libatspi2.0-0
    #   - libbrotli1
    #   - libcairo-gobject2
    #   - libcairo2
    #   - libdatrie1
    #   - libdrm2
    #   - libegl1
    #   - libenchant-2-2
    #   - libepoxy0
    #   - libfontconfig1
    #   - libfreetype6
    #   - libfribidi0
    #   - libgbm1
    #   - libgdk-pixbuf2.0-0
    #   - libgl1
    #   - libglvnd0
    #   - libglx0
    #   - libgraphite2-3
    #   - libgstreamer-gl1.0-0
    #   - libgstreamer-plugins-base1.0-0
    #   - libgstreamer1.0-0
    #   - libgtk-3-0
    #   - libgudev-1.0-0
    #   - libharfbuzz-icu0
    #   - libharfbuzz0b
    #   - libhyphen0
    #   - libicu66
    #   - libjavascriptcoregtk-4.0-18
    #   - libjpeg-turbo8
    #   - liblcms2-2
    #   - libnotify4
    #   - libopengl0
    #   - libopenjp2-7
    #   - liborc-0.4-0
    #   - libpango-1.0-0
    #   - libpangocairo-1.0-0
    #   - libpangoft2-1.0-0
    #   - libpixman-1-0
    #   - libpng16-16
    #   - libpsl5
    #   - libsecret-1-0
    #   - libsoup2.4-1
    #   - libthai0
    #   - libwayland-client0
    #   - libwayland-cursor0
    #   - libwayland-egl1
    #   - libwayland-server0
    #   - libwebkit2gtk-4.0-37
    #   - libwebp6
    #   - libwebpdemux2
    #   - libwoff1
    #   - libx11-6
    #   - libx11-xcb1
    #   - libxau6
    #   - libxcb-render0
    #   - libxcb-shm0
    #   - libxcb1
    #   - libxcomposite1
    #   - libxcursor1
    #   - libxdamage1
    #   - libxdmcp6
    #   - libxext6
    #   - libxfixes3
    #   - libxi6
    #   - libxinerama1
    #   - libxkbcommon0
    #   - libxml2
    #   - libxrandr2
    #   - libxrender1
    #   - libxslt1.1
