use std::str::FromStr;

#[derive(Debug, Clone)]
pub enum Languages {
    Afrikaans,
    Albanian,
    Amharic,
    Arabic,
    Armenian,
    Azerbaijani,
    Basque,
    Belarusian,
    Bengali,
    Bosnian,
    Bulgarian,
    Catalan,
    Chichewa,
    ChineseSimplified,
    ChineseTraditional,
    Corsican,
    Croatian,
    Czech,
    Danish,
    Dutch,
    English,
    Esperanto,
    Estonian,
    Filipino,
    Finnish,
    French,
    Frisian,
    Galician,
    Georgian,
    German,
    Greek,
    Guarani,
    Gujarati,
    Haitian,
    Hausa,
    Hawaiian,
    Hebrew,
    Hindi,
    Hungarian,
    Icelandic,
    Igbo,
    Indonesian,
    Irish,
    Italian,
    Japanese,
    Javanese,
    Kannada,
    Kazakh,
    Khmer,
    Kinyarwanda,
    Korean,
    Krio,
    KurdishKurmanji,
    KurdishSorani,
    Kyrgyz,
    Laothian,
    Latin,
    Latvian,
    Lingala,
    Lithuanian,
    Luganda,
    Macedonian,
    Malagasy,
    Malay,
    Malayalam,
    Maltese,
    Maori,
    Marathi,
    Mongolian,
    Myanmar,
    Nepali,
    Norwegian,
    Odia,
    Oromo,
    Pashto,
    Polish,
    Portuguese,
    Punjabi,
    Quechua,
    Romanian,
    Russian,
    Scots,
    Serbian,
    Sesotho,
    Shona,
    Sindhi,
    Sinhala,
    Slovak,
    Slovenian,
    Somali,
    Spanish,
    Sundanese,
    Swahili,
    Swedish,
    Tajik,
    Tamil,
    Tatar,
    Telugu,
    Thai,
    Tigrinya,
    Tsonga,
    Turkish,
    Turkmen,
    Twi,
    Ukrainian,
    Urdu,
    Uyghur,
    Uzbek,
    Vietnamese,
    Welsh,
    Xhosa,
    Yiddish,
    Yoruba,
    Zulu,
}

impl FromStr for Languages {
    type Err = String;
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "af" => Ok(Languages::Afrikaans),
            "sq" => Ok(Languages::Albanian),
            "am" => Ok(Languages::Amharic),
            "ar" => Ok(Languages::Arabic),
            "hy" => Ok(Languages::Armenian),
            "az" => Ok(Languages::Azerbaijani),
            "eu" => Ok(Languages::Basque),
            "be" => Ok(Languages::Belarusian),
            "bn" => Ok(Languages::Bengali),
            "bs" => Ok(Languages::Bosnian),
            "bg" => Ok(Languages::Bulgarian),
            "ca" => Ok(Languages::Catalan),
            "ny" => Ok(Languages::Chichewa),
            "zh-CN" => Ok(Languages::ChineseSimplified),
            "zh-TW" => Ok(Languages::ChineseTraditional),
            "co" => Ok(Languages::Corsican),
            "hr" => Ok(Languages::Croatian),
            "cs" => Ok(Languages::Czech),
            "da" => Ok(Languages::Danish),
            "nl" => Ok(Languages::Dutch),
            "en" => Ok(Languages::English),
            "eo" => Ok(Languages::Esperanto),
            "et" => Ok(Languages::Estonian),
            "tl" => Ok(Languages::Filipino),
            "fi" => Ok(Languages::Finnish),
            "fr" => Ok(Languages::French),
            "fy" => Ok(Languages::Frisian),
            "gl" => Ok(Languages::Galician),
            "ka" => Ok(Languages::Georgian),
            "de" => Ok(Languages::German),
            "el" => Ok(Languages::Greek),
            "gn" => Ok(Languages::Guarani),
            "gu" => Ok(Languages::Gujarati),
            "ht" => Ok(Languages::Haitian),
            "ha" => Ok(Languages::Hausa),
            "haw" => Ok(Languages::Hawaiian),
            "iw" => Ok(Languages::Hebrew),
            "hi" => Ok(Languages::Hindi),
            "hu" => Ok(Languages::Hungarian),
            "is" => Ok(Languages::Icelandic),
            "ig" => Ok(Languages::Igbo),
            "id" => Ok(Languages::Indonesian),
            "ga" => Ok(Languages::Irish),
            "it" => Ok(Languages::Italian),
            "ja" => Ok(Languages::Japanese),
            "jw" => Ok(Languages::Javanese),
            "kn" => Ok(Languages::Kannada),
            "kk" => Ok(Languages::Kazakh),
            "km" => Ok(Languages::Khmer),
            "rw" => Ok(Languages::Kinyarwanda),
            "ko" => Ok(Languages::Korean),
            "kri" => Ok(Languages::Krio),
            "ku" => Ok(Languages::KurdishKurmanji),
            "ckb" => Ok(Languages::KurdishSorani),
            "ky" => Ok(Languages::Kyrgyz),
            "lo" => Ok(Languages::Laothian),
            "la" => Ok(Languages::Latin),
            "lv" => Ok(Languages::Latvian),
            "ln" => Ok(Languages::Lingala),
            "lt" => Ok(Languages::Lithuanian),
            "lg" => Ok(Languages::Luganda),
            "mk" => Ok(Languages::Macedonian),
            "mg" => Ok(Languages::Malagasy),
            "ms" => Ok(Languages::Malay),
            "ml" => Ok(Languages::Malayalam),
            "mt" => Ok(Languages::Maltese),
            "mi" => Ok(Languages::Maori),
            "mr" => Ok(Languages::Marathi),
            "mn" => Ok(Languages::Mongolian),
            "my" => Ok(Languages::Myanmar),
            "ne" => Ok(Languages::Nepali),
            "no" => Ok(Languages::Norwegian),
            "or" => Ok(Languages::Odia),
            "om" => Ok(Languages::Oromo),
            "ps" => Ok(Languages::Pashto),
            "pl" => Ok(Languages::Polish),
            "pt" => Ok(Languages::Portuguese),
            "pa" => Ok(Languages::Punjabi),
            "qu" => Ok(Languages::Quechua),
            "ro" => Ok(Languages::Romanian),
            "ru" => Ok(Languages::Russian),
            "gd" => Ok(Languages::Scots),
            "sr" => Ok(Languages::Serbian),
            "st" => Ok(Languages::Sesotho),
            "sn" => Ok(Languages::Shona),
            "sd" => Ok(Languages::Sindhi),
            "si" => Ok(Languages::Sinhala),
            "sk" => Ok(Languages::Slovak),
            "sl" => Ok(Languages::Slovenian),
            "so" => Ok(Languages::Somali),
            "es" => Ok(Languages::Spanish),
            "su" => Ok(Languages::Sundanese),
            "sw" => Ok(Languages::Swahili),
            "sv" => Ok(Languages::Swedish),
            "tg" => Ok(Languages::Tajik),
            "ta" => Ok(Languages::Tamil),
            "tt" => Ok(Languages::Tatar),
            "te" => Ok(Languages::Telugu),
            "th" => Ok(Languages::Thai),
            "ti" => Ok(Languages::Tigrinya),
            "ts" => Ok(Languages::Tsonga),
            "tr" => Ok(Languages::Turkish),
            "tk" => Ok(Languages::Turkmen),
            "tw" => Ok(Languages::Twi),
            "uk" => Ok(Languages::Ukrainian),
            "ur" => Ok(Languages::Urdu),
            "ug" => Ok(Languages::Uyghur),
            "uz" => Ok(Languages::Uzbek),
            "vi" => Ok(Languages::Vietnamese),
            "cy" => Ok(Languages::Welsh),
            "xh" => Ok(Languages::Xhosa),
            "yi" => Ok(Languages::Yiddish),
            "yo" => Ok(Languages::Yoruba),
            "zu" => Ok(Languages::Zulu),
            _ => Err(format!(
                "unknown language: {}. Make sure to use all the supported languages",
                s
            )),
        }
    }
}

impl Languages {
    pub fn as_code(l: &Languages) -> &'static str {
        match l {
            Languages::Afrikaans => "af",
            Languages::Albanian => "sq",
            Languages::Amharic => "am",
            Languages::Arabic => "ar",
            Languages::Armenian => "hy",
            Languages::Azerbaijani => "az",
            Languages::Basque => "eu",
            Languages::Belarusian => "be",
            Languages::Bengali => "bn",
            Languages::Bosnian => "bs",
            Languages::Bulgarian => "bg",
            Languages::Catalan => "ca",
            Languages::Chichewa => "ny",
            Languages::ChineseSimplified => "zh-CN",
            Languages::ChineseTraditional => "zh-TW",
            Languages::Corsican => "co",
            Languages::Croatian => "hr",
            Languages::Czech => "cs",
            Languages::Danish => "da",
            Languages::Dutch => "nl",
            Languages::English => "en",
            Languages::Esperanto => "eo",
            Languages::Estonian => "et",
            Languages::Filipino => "tl",
            Languages::Finnish => "fi",
            Languages::French => "fr",
            Languages::Frisian => "fy",
            Languages::Galician => "gl",
            Languages::Georgian => "ka",
            Languages::German => "de",
            Languages::Greek => "el",
            Languages::Guarani => "gn",
            Languages::Gujarati => "gu",
            Languages::Haitian => "ht",
            Languages::Hausa => "ha",
            Languages::Hawaiian => "haw",
            Languages::Hebrew => "iw",
            Languages::Hindi => "hi",
            Languages::Hungarian => "hu",
            Languages::Icelandic => "is",
            Languages::Igbo => "ig",
            Languages::Indonesian => "id",
            Languages::Irish => "ga",
            Languages::Italian => "it",
            Languages::Japanese => "ja",
            Languages::Javanese => "jw",
            Languages::Kannada => "kn",
            Languages::Kazakh => "kk",
            Languages::Khmer => "km",
            Languages::Kinyarwanda => "rw",
            Languages::Korean => "ko",
            Languages::Krio => "kri",
            Languages::KurdishKurmanji => "ku",
            Languages::KurdishSorani => "ckb",
            Languages::Kyrgyz => "ky",
            Languages::Laothian => "lo",
            Languages::Latin => "la",
            Languages::Latvian => "lv",
            Languages::Lingala => "ln",
            Languages::Lithuanian => "lt",
            Languages::Luganda => "lg",
            Languages::Macedonian => "mk",
            Languages::Malagasy => "mg",
            Languages::Malay => "ms",
            Languages::Malayalam => "ml",
            Languages::Maltese => "mt",
            Languages::Maori => "mi",
            Languages::Marathi => "mr",
            Languages::Mongolian => "mn",
            Languages::Myanmar => "my",
            Languages::Nepali => "ne",
            Languages::Norwegian => "no",
            Languages::Odia => "or",
            Languages::Oromo => "om",
            Languages::Pashto => "ps",
            Languages::Polish => "pl",
            Languages::Portuguese => "pt",
            Languages::Punjabi => "pa",
            Languages::Quechua => "qu",
            Languages::Romanian => "ro",
            Languages::Russian => "ru",
            Languages::Scots => "gd",
            Languages::Serbian => "sr",
            Languages::Sesotho => "st",
            Languages::Shona => "sn",
            Languages::Sindhi => "sd",
            Languages::Sinhala => "si",
            Languages::Slovak => "sk",
            Languages::Slovenian => "sl",
            Languages::Somali => "so",
            Languages::Spanish => "es",
            Languages::Sundanese => "su",
            Languages::Swahili => "sw",
            Languages::Swedish => "sv",
            Languages::Tajik => "tg",
            Languages::Tamil => "ta",
            Languages::Tatar => "tt",
            Languages::Telugu => "te",
            Languages::Thai => "th",
            Languages::Tigrinya => "ti",
            Languages::Tsonga => "ts",
            Languages::Turkish => "tr",
            Languages::Turkmen => "tk",
            Languages::Twi => "tw",
            Languages::Ukrainian => "uk",
            Languages::Urdu => "ur",
            Languages::Uyghur => "ug",
            Languages::Uzbek => "uz",
            Languages::Vietnamese => "vi",
            Languages::Welsh => "cy",
            Languages::Xhosa => "xh",
            Languages::Yiddish => "yi",
            Languages::Yoruba => "yo",
            Languages::Zulu => "zu",
        }
    }
}
