import { OfflineDictAbbrs } from "./offline-mode";
import { Theme } from "./theme";

export const offlineDictionaries = {
    English: "en",
    French: "fr",
    German: "de",
    Spanish: "es",
    Portuguese: "pt",
    Italian: "it",
    Persian: "fa",
    "Chinese (Simplified)": "zh-CN",
    Arabic: "ar",
} as const;

export const onlineDictionaries = {
    Afrikaans: "af",
    Albanian: "sq",
    Amharic: "am",
    Arabic: offlineDictionaries.Arabic,
    Armenian: "hy",
    Azerbaijani: "az",
    Basque: "eu",
    Belarusian: "be",
    Bengali: "bn",
    Bosnian: "bs",
    Bulgarian: "bg",
    Catalan: "ca",
    Chichewa: "ny",
    "Chinese (Simplified)": offlineDictionaries["Chinese (Simplified)"],
    "Chinese (Traditional)": "zh-TW",
    Corsican: "co",
    Croatian: "hr",
    Czech: "cs",
    Danish: "da",
    Dutch: "nl",
    English: offlineDictionaries.English,
    Esperanto: "eo",
    Estonian: "et",
    Filipino: "tl",
    Finnish: "fi",
    French: offlineDictionaries.French,
    Frisian: "fy",
    Galician: "gl",
    Georgian: "ka",
    German: offlineDictionaries.German,
    Greek: "el",
    Guarani: "gn",
    Gujarati: "gu",
    "Haitian Creole": "ht",
    Hausa: "ha",
    Hawaiian: "haw",
    Hebrew: "iw",
    Hindi: "hi",
    Hungarian: "hu",
    Icelandic: "is",
    Igbo: "ig",
    Indonesian: "id",
    Irish: "ga",
    Italian: offlineDictionaries.Italian,
    Japanese: "ja",
    Javanese: "jw",
    Kannada: "kn",
    Kazakh: "kk",
    Khmer: "km",
    Kinyarwanda: "rw",
    Korean: "ko",
    "Krio (Sierra Leone)": "kri",
    "Kurdish (Kurmanji)": "ku",
    "Kurdish (Soranî)": "ckb",
    Kyrgyz: "ky",
    Laothian: "lo",
    Latin: "la",
    Latvian: "lv",
    Lingala: "ln",
    Lithuanian: "lt",
    Luganda: "lg",
    Macedonian: "mk",
    Malagasy: "mg",
    Malay: "ms",
    Malayalam: "ml",
    Maltese: "mt",
    Maori: "mi",
    Marathi: "mr",
    Mongolian: "mn",
    "Myanmar (Burmese)": "my",
    Nepali: "ne",
    Norwegian: "no",
    "Odia (Oriya)": "or",
    Oromo: "om",
    Pashto: "ps",
    Persian: offlineDictionaries.Persian,
    Polish: "pl",
    Portuguese: offlineDictionaries.Portuguese,
    Punjabi: "pa",
    Quechua: "qu",
    Romanian: "ro",
    Russian: "ru",
    "Scots Gaelic": "gd",
    Serbian: "sr",
    Sesotho: "st",
    Shona: "sn",
    Sindhi: "sd",
    Sinhala: "si",
    Slovak: "sk",
    Slovenian: "sl",
    Somali: "so",
    Spanish: offlineDictionaries.Spanish,
    Sundanese: "su",
    Swahili: "sw",
    Swedish: "sv",
    Tajik: "tg",
    Tamil: "ta",
    Tatar: "tt",
    Telugu: "te",
    Thai: "th",
    Tigrinya: "ti",
    Tsonga: "ts",
    Turkish: "tr",
    Turkmen: "tk",
    Twi: "tw",
    Ukrainian: "uk",
    Urdu: "ur",
    Uyghur: "ug",
    Uzbek: "uz",
    Vietnamese: "vi",
    Welsh: "cy",
    Xhosa: "xh",
    Yiddish: "yi",
    Yoruba: "yo",
    Zulu: "zu",
} as const;

export type CountriesNames = keyof typeof onlineDictionaries;
export type CountriesAbbrs = typeof onlineDictionaries[CountriesNames];
export type SavedConfig = {
    theme: Theme;
    activeTab: 'online' | 'offline';
    from: CountriesAbbrs | 'auto';
    to: CountriesAbbrs;
    selectedOfflineDict?: OfflineDictAbbrs;
    downloadedDicts?: OfflineDictAbbrs[];
    x: number;
    y: number;
    width: number;
    height: number;
    shouldTranslateClipboard: boolean;
    shouldTranslateSelectedText: boolean;
}
