
export const offlineDictionaries = {
    English: "en",
    French: "fr",
    German: "de",
    Spanish: "es",
    Italian: "it",
    Persian: "fa",
    Arabic: "ar",
} as const;

export const onlineDictionaries = {
    Afrikaans: "af",
    Bulgarian: "bg",
    Bengali: "bn",
    Bosnian: "bs",
    Catalan: "ca",
    Czech: "cs",
    Welsh: "cy",
    Danish: "da",
    Greek: "el",
    Esperanto: "eo",
    Estonian: "et",
    Finnish: "fi",
    Gujarati: "gu",
    Hindi: "hi",
    Croatian: "hr",
    Hungarian: "hu",
    Armenian: "hy",
    Indonesian: "id",
    Icelandic: "is",
    Japanese: "ja",
    Javanese: "jw",
    Khmer: "km",
    Kannada: "kn",
    Korean: "ko",
    Latin: "la",
    Latvian: "lv",
    Macedonian: "mk",
    Malayalam: "ml",
    Marathi: "mr",
    "Myanmar (Burmese)": "my",
    Nepali: "ne",
    Dutch: "nl",
    Norwegian: "no",
    Polish: "pl",
    Portuguese: "pt",
    Romanian: "ro",
    Russian: "ru",
    Sinhala: "si",
    Slovak: "sk",
    Albanian: "sq",
    Serbian: "sr",
    Sundanese: "su",
    Swedish: "sv",
    Swahili: "sw",
    Tamil: "ta",
    Telugu: "te",
    Thai: "th",
    Filipino: "tl",
    Turkish: "tr",
    Ukrainian: "uk",
    Urdu: "ur",
    Vietnamese: "vi",
    Chinese: "zh-CN",
    ...offlineDictionaries,
} as const;